/**
 * SEO utilities — barrel export. Import from "@/lib/seo".
 *
 * NOTE: robots.txt and sitemap.xml are generated by app/robots.ts and
 * app/sitemap.ts (Next.js App Router convention) rather than here — a
 * documented deviation from Chapter 7 §9. See docs/decision-log.md.
 */
export { buildMetadata, buildRootMetadata } from "@/lib/seo/metadata";
export {
  organizationSchema,
  websiteSchema,
  breadcrumbSchema,
  faqSchema,
} from "@/lib/seo/structured-data";
